### ISSUE TITLE
Error in Tensorflow 1.9 installation on HPC

### ISSUE THREAD

**Issue by abhudev** [vineetm/ell-881-2018-deep-learning#3]
I installed Tensorflow on HPC but ran into a problem while importing it, the error seems to be related to GLIBC version. Since we are supposed to use v1.9 in this course, it will be problematic if we are not able to install and use it on HPC.

Full error message:
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/home/cse/btech/cs1150424/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/cse/btech/cs1150424/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/cse/btech/cs1150424/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/cse/btech/cs1150424/anaconda3/envs/tf/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/cse/btech/cs1150424/anaconda3/envs/tf/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /home/cse/btech/cs1150424/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cse/btech/cs1150424/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/cse/btech/cs1150424/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/cse/btech/cs1150424/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/cse/btech/cs1150424/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/cse/btech/cs1150424/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/cse/btech/cs1150424/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/cse/btech/cs1150424/anaconda3/envs/tf/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/cse/btech/cs1150424/anaconda3/envs/tf/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /home/cse/btech/cs1150424/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by Maxaravind** [comment]
It seems to be a cuda driver version miss match. Can you tell me how you installed tensorflow on hpc? Did you do it in a anaconda virtual env?

**Comment by abhudev** [comment]
I followed the instructions given by Vineet sir in the lecture 1 folder and did it in anaconda virtual env using pip. The CUDA version on HPC is 8, how do I get around this?

**Comment by Maxaravind** [comment]
Unfortunately Tensorflow version 1.9 requires cuda 9(see: https://www.tensorflow.org/install/install_sources#tested_source_configurations). As of now i am unaware of any way to install a different cuda driver in hpc since they don't provide us root access. What you can do is use the default tensorflow version provided  in the hpc and do your experiments(try: module load apps/tensorflow/1.5.0/gpu in hpc)(you can also do module avail in the hpc to see if a new version of tensorflow is available), for the time being. Use the tensorflow version provided by hpc and not the one from your virtual env.

**Comment by Maxaravind** [comment]
You can try with 9.2, people have done that. You can try something along these lines: https://hk.saowen.com/a/a9cc5b7c90a6f350850d8554c018f7415981fc8d470b481c90afd7573f5e12cd

**Comment by vineetm** [comment]
@Maxaravind Thanks for finding about 9.2 @abhudev Were you able to do a hello world in tensorflow?

**Comment by abhudev** [comment]
No Sir, I have not tried it out yet, I will try to do as soon as possible. @Maxaravind  Thank you for the tutorial, I will comment again if I find any problems while trying to install.

**Comment by vineetm** [comment]
@Maxaravind @VinayKyatham I need your help in making sure Tensorflow 1.9 works with GPU on HPC. 
@anshumitts mentioned in class yesterday that he could install tf1.9, and you can try using his virtualenv.

Once you have installed Tensorflow, do some kind of hello world to ensure it is installed. You should also check if tf is able to use GPUs as indicated [here](https://github.com/vineetm/notes/blob/master/tensorflow/install.md)

**Comment by anshumitts** [comment]
Hi,
One small correction I have tensorflow 1.8 not 1.9

**Comment by anshumitts** [comment]
Please do the following steps:

```
conda create -n tensorflow python=3.6 anaconda
conda activate tensorflow
conda install -c anaconda tensorflow 
```

You should have tensorflow 1.10 now

**Comment by Maxaravind** [comment]
@vineetm @anshumitts 

Tf 1.9.0 is already installed on the hpc, you don't need to install it on your virtual environment separately 

Please do:

module load apps/pythonpackages/3.6.0/tensorflow/1.9.0/gpu

That's all you need to do. This is the best way to do it.

**Comment by abhudev** [comment]
@Maxaravind  I have set up anaconda, do I need to remove it to get this working?
